<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CORPLPW100314" failures="4" tests="13" name="Command line test" time="331.282" errors="0" timestamp="2021-04-17T20:59:52 IST">
  <testcase classname="com.athmatest.qa.testcases.NewRegistrationTest" name="newRegistration" time="10.703">
    <failure type="org.openqa.selenium.StaleElementReferenceException" message="stale element reference: element is not attached to the page document
  (Session info: chrome=89.0.4389.128)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;CORPLPW100314&amp;apos;, ip: &amp;apos;10.120.0.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;15.0.2&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 89.0.4389.128, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: C:\Users\339154\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:62119}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: fd793a82101ff1c5a51b47826d878e43">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=89.0.4389.128)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'CORPLPW100314', ip: '10.120.0.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 89.0.4389.128, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: C:\Users\339154\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:62119}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: fd793a82101ff1c5a51b47826d878e43
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:166)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy13.getText(Unknown Source)
at com.athmatest.qa.pages.NewRegistrationPage.newpatientRegistrationPageTitle(NewRegistrationPage.java:63)
at com.athmatest.qa.testcases.NewRegistrationTest.newRegistration(NewRegistrationTest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 46 stack frames]]>
    </failure>
  </testcase> <!-- newRegistration -->
  <testcase classname="com.athmatest.qa.testcases.NewRegistrationTest" name="newRegistration" time="24.739"/>
  <testcase classname="com.athmatest.qa.testcases.NewRegistrationTest" name="newRegistration" time="23.779"/>
  <testcase classname="com.athmatest.qa.testcases.NewRegistrationTest" name="newRegistration" time="23.488"/>
  <testcase classname="com.athmatest.qa.testcases.NewRegistrationTest" name="newRegistration" time="24.082"/>
  <testcase classname="com.athmatest.qa.testcases.Sample1Test" name="myFirstTest" time="0.006"/>
  <testcase classname="com.athmatest.qa.testcases.Sample1Test" name="mySecondTest" time="0.053"/>
  <testcase classname="com.athmatest.qa.testcases.Sample1Test" name="myThirdTest" time="0.015"/>
  <testcase classname="com.athmatest.qa.testcases.Sample1Test" name="myFourthTest" time="0.023"/>
  <testcase classname="com.athmatest.qa.testcases.SampleTest" name="myFirstTest" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.athmatest.qa.testcases.SampleTest.myFirstTest(SampleTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- myFirstTest -->
  <testcase classname="com.athmatest.qa.testcases.SampleTest" name="mySecondTest" time="7.514">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.athmatest.qa.testcases.SampleTest.mySecondTest(SampleTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- mySecondTest -->
  <testcase classname="com.athmatest.qa.testcases.SampleTest" name="myThirdTest" time="8.255">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.athmatest.qa.testcases.SampleTest.myThirdTest(SampleTest.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- myThirdTest -->
  <testcase classname="com.athmatest.qa.testcases.SampleTest" name="myFourthTest" time="8.179"/>
</testsuite> <!-- Command line test -->
